version: 2.1
jobs:
  build:
    working_directory: ~/node-omnibus
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: 'Run Jest and Collect Coverage Reports'
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
